In [ ]:
#importing libraries

import numpy as np
import pandas as pd

In [ ]:
# reading the CSV file (Cafe Sales Data)

df = pd.read_csv('/workspaces/data_cleaning_1/data/raw/Cafe Sales.csv')

In [4]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [6]:
print(f'cafe sales data contains {sum(df.duplicated())} duplicate records.')

cafe sales data contains 0 duplicate records.

In [7]:
df.isna().sum() * 100 / df.shape[0]

Transaction ID       0.00
Item                 3.33
Quantity             1.38
Price Per Unit       1.79
Total Spent          1.73
Payment Method      25.79
Location            32.65
Transaction Date     1.59
dtype: float64

In [8]:
#if you look here under location column there are unkonwn and NaN which means the above percentage shows only NaN percentage but not Unknown. so data impurities.
df.head(15)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21

In [9]:
set(df.columns)

{'Item',
 'Location',
 'Payment Method',
 'Price Per Unit',
 'Quantity',
 'Total Spent',
 'Transaction Date',
 'Transaction ID'}

In [10]:
#inspecting unique values in all columns except 'Transaction Id'
df_cols = set(df.columns)
exclude = {'Transaction ID'}
df_cols = df_cols.difference(exclude)
df_cols = list(df_cols)

for col in df_cols:
  print(f'{col}:\n{df[col].unique()}', end = '\n\n')

Payment Method:
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

Item:
<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

Price Per Unit:
<StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str

Transaction Date:
<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
 ...
 '2023-08-01', '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
 '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
Length: 368, dtype: str

Location:
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

Total Spent:
<StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

Quantity:
<StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str

In [12]:
#replacing error and unknown
df.replace(['ERROR', 'UNKNOWN'], np.nan)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [13]:
df = df.replace(['ERROR', 'UNKNOWN'], np.nan)

df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [14]:
#changing quantity as integer as it contains nan
df['Quantity'].astype('Int64')

0       2
1       4
2       4
3       2
4       2
       ..
9995    2
9996    3
9997    4
9998    3
9999    3
Name: Quantity, Length: 10000, dtype: Int64

In [15]:
#changed all the below data types for accuarcy

df['Quantity'] = df['Quantity'].astype('Int64')
df[['Price Per Unit', 'Total Spent']] = df[['Price Per Unit', 'Total Spent']].astype('float')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

In [16]:
df.isna().sum() * 100 / df.shape[0]

Transaction ID       0.00
Item                 9.69
Quantity             4.79
Price Per Unit       5.33
Total Spent          5.02
Payment Method      31.78
Location            39.61
Transaction Date     4.60
dtype: float64

In [17]:
df= df.dropna(subset= ['Transaction Date'])
df.info()

<class 'pandas.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              8613 non-null   str
 2   Quantity          9086 non-null   Int64
 3   Price Per Unit    9034 non-null   float64
 4   Total Spent       9064 non-null   float64
 5   Payment Method    6525 non-null   str
 6   Location          5761 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 680.1 KB

In [18]:
df.isna().sum() * 100 / df.shape[0]

Transaction ID       0.000000
Item                 9.716981
Quantity             4.758910
Price Per Unit       5.303983
Total Spent          4.989518
Payment Method      31.603774
Location            39.612159
Transaction Date     0.000000
dtype: float64

In [19]:
#Filling missing columns with "INA" for Payment method and Location instead of deleting as it gives more missing info for calutions

df[['Payment Method', 'Location']] = df[['Payment Method', 'Location']].fillna('INA')

In [20]:
df.isna().sum() * 100 / df.shape[0]

Transaction ID      0.000000
Item                9.716981
Quantity            4.758910
Price Per Unit      5.303983
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [ ]:
#Replacting Item values with mode
df['Item'].mode(0)

df['Item'] = df['Item'].fillna(df['Item'].mode()[0])

In [24]:
df.isna().sum() * 100/ df.shape[0]

Transaction ID      0.000000
Item                9.716981
Quantity            4.758910
Price Per Unit      9.716981
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [21]:
# Price per unit is a dependant item
#Groupby  each category for disticnt price
df.groupby('Item')['Price Per Unit'].value_counts()

Item      Price Per Unit
Cake      3.0               1031
Coffee    2.0               1069
Cookie    1.0                976
Juice     3.0               1065
Salad     5.0               1035
Sandwich  4.0               1027
Smoothie  4.0                990
Tea       1.5                965
Name: count, dtype: int64

In [22]:
df.groupby('Item')['Price Per Unit'].median()

Item
Cake        3.0
Coffee      2.0
Cookie      1.0
Juice       3.0
Salad       5.0
Sandwich    4.0
Smoothie    4.0
Tea         1.5
Name: Price Per Unit, dtype: float64

In [23]:
#lambda is used here (when ever you pick an item groupby in that particular category and prepare median)

df.groupby('Item')['Price Per Unit'].transform(lambda x: x.fillna(x.median()))

df['Price Per Unit'] = df.groupby('Item')['Price Per Unit'].transform(lambda x: x.fillna(x.median()))

df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,INA,INA,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,INA,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,INA,2023-03-02
9998,TXN_7695629,Cookie,3,1.0,3.0,Digital Wallet,INA,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [25]:
df.isna().sum() * 100/ df.shape[0]

Transaction ID      0.000000
Item                9.716981
Quantity            4.758910
Price Per Unit      9.716981
Total Spent         4.989518
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [26]:
#filling missing info of Total spent by the product of Price spent * quantity

df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])

In [27]:
df.isna().sum() *100/df.shape[0]

Transaction ID      0.000000
Item                9.716981
Quantity            4.758910
Price Per Unit      9.716981
Total Spent         0.723270
Payment Method      0.000000
Location            0.000000
Transaction Date    0.000000
dtype: float64

In [28]:
# Storing clean data
df.to_csv('/workspaces/data_cleaning_1/data/clean/Cafe Sales(Clean).csv', index = False)